export class InventoryModel {
  public _id!: string; // generated by mongoDB
  public title!: string;
  public description!: string;
  public completed!: boolean;
  public image!: string;
  public quantity!: number;
  public category!: string;
  public subcategory!: string;
  public place!: string;
  public expiration_date!: string;
  public createdAt!: Date; // generated by mongoDB
  public updatedAt!: Date; // generated by mongoDB
  constructor(model?: any) {
    Object.assign(this, model);
  }
  }
  
  