export class DishCardModel {
    public _id!: string; // generated by mongoDB
    public title!: string;
    public description!: string;
    public image!: string;
    public time!: number;
    public category!: string;
    public info!: string;
    public status!: string;
    public ingredients: string[] = [];
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  }
  