export class InventoryModel {
    public _id!: string; // generated by mongoDB
    public name!: string;
    public image!: string;
    public quantity!: number;
    public category!: string;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  }
  
  