import { Component, OnInit } from '@angular/core';
import { DishCardModel } from 'src/app/global/models/Dish/dish.model';
import { DishService } from 'src/app/global/services/cook/dish.service';
import { SocketsService } from 'src/app/global/services/sockets/sockets.service';

@Component({
  selector: 'fridge-inventory',
  templateUrl: './inventory.component.html',
  styleUrls: ['./inventory.component.scss']
})
export class InventoryComponent implements OnInit {

  public status="Add";
  public dishes: DishCardModel[] = [];

  constructor(
    private dishService: DishService,
    private socketService: SocketsService) { }

  ngOnInit(): void { 
    this.getAllDishes();
    // Susbcribe to socket event and set callback
    //if soemone publishes dish_update run the functions
    this.socketService.subscribe("dish_update", (data: any) => {
      this.getAllDishes();
    });
  }

  private getAllDishes(): void {
    this.dishService.getAllDishes().subscribe((result) => {
      this.dishes = result;
    });
  }

  isInputFocused: boolean = false;

  onInputFocus(event: FocusEvent): void {
    this.isInputFocused = true;
  }

  onInputBlur(event: FocusEvent): void {
    this.isInputFocused = false;
  }

  fruits = [
    { title: 'Apple' ,image: 'assets/fridge/fruits/apple.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Pear' ,image: 'assets/fridge/fruits/pear.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Gala"],info:"Lunch",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Orange' ,image: 'assets/fridge/fruits/orange.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Fisaa","Fish"],info:"Dinner",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to " },
    { title: 'Banana' ,image: 'assets/fridge/fruits/banana.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
  ];

  vegetables = [
    { title: 'Carrot' ,image: 'assets/fridge/vegetables/carrot.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Tomato' ,image: 'assets/fridge/vegetables/tomato.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Cucumber' ,image: 'assets/fridge/vegetables/cucumber.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Onion' ,image: 'assets/fridge/vegetables/onion.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Red Pepper' ,image: 'assets/fridge/vegetables/redpepper.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Green Pepper' ,image: 'assets/fridge/vegetables/greenpepper.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Orange Pepper' ,image: 'assets/fridge/vegetables/orangepepper.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},

  ];

  meatnfish = [
    { title: 'Apple' ,image: 'assets/fridge/fruits/apple.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Pear' ,image: 'assets/fridge/fruits/pear.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Gala"],info:"Lunch",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Orange' ,image: 'assets/fridge/fruits/orange.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Fisaa","Fish"],info:"Dinner",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to " },
    { title: 'Banana' ,image: 'assets/fridge/fruits/banana.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
  ];

  dairy = [
    { title: 'Apple' ,image: 'assets/fridge/fruits/apple.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Pear' ,image: 'assets/fridge/fruits/pear.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Gala"],info:"Lunch",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Orange' ,image: 'assets/fridge/fruits/orange.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Fisaa","Fish"],info:"Dinner",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to " },
    { title: 'Banana' ,image: 'assets/fridge/fruits/banana.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
  ];

  drinks = [
    { title: 'Apple' ,image: 'assets/fridge/fruits/apple.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Pear' ,image: 'assets/fridge/fruits/pear.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Gala"],info:"Lunch",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
    { title: 'Orange' ,image: 'assets/fridge/fruits/orange.png',time: "20",category: "Seafood",status : "Cooking",ingredients : ["Fisaa","Fish"],info:"Dinner",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to " },
    { title: 'Banana' ,image: 'assets/fridge/fruits/banana.png',time: "20",category: "Seafood",status : "Cooking" , ingredients : ["Gala","Fish"],info:"Breakfast",description : "Soak the shrimp – In a large bowl, mix together the milk, ½ teaspoon salt, the black pepper, half the granulated garlic, half the paprika, and half of the oregano. Add in the shrimp and let soak for 10 minutes.Coat the shrimp – Once the shrimp is finished soaking, shake free of excess milk. Mix together the remaining spices and flour on a plate and coat the shrimp well. Make sure you coat the shrimp really well with flour. Coat them several times with the seasoned flour. You should not be able to see the shrimp under the flour.Fry the shrimp – Heat the oil to 375 degrees and fry each batch of shrimp for about 1-2 minutes or until it’s nice and crispy.Serve – Allow the shrimp to "},
  ];


  selectedCategory: string | null = null;

  selectCategory(item: any): void {
    this.selectedCategory = this.selectedCategory === item.category ? null : item.category;
    console.log(this.selectedCategory);
  }

  // toggleCategory(category: string): void {
  //   console.log('Category clicked:', category);
  //   if (this.selectedCategory !== category) {
  //     this.selectedCategory = category;
  //     console.log('Category icon:', this.selectedCategory);
  //   }
  // }

}
